---
- device:
  id: UUID
  type: {'server', 'vm'}
  hostname: STRING
  datacenter: {'wdc', 'sc', 'ams', 'blr'}

  - server:
    model: STRING
    serial: STRING
    service_tag: STRING
    role: {'bare metal', 'esxi'}
    primary_ip_addr: STRING
    primary_mac_addr: STRING
    oob_ip_addr: STRING
    cpu_model: STRING
    cpu_count: INT
    memory: INT
    disk_count: INT
    disks:
      disk0: {model: STRING, capacity: FLOAT, type: {'ssd', 'hdd'}}
      disk1: {model: STRING, capacity: FLOAT, type: {'ssd', 'hdd'}} 
    nic_count: INT
    nics:
      nic0: {ipv4_addr: STRING, ipv4_prefix: INT, ipv4_gateway: STRING, mac_addr: STRING}
      nic1: {ipv6_addr: STRING, ipv6_prefix: INT, ipv6_gateway: STRING, mac_addr: STRING}
    os: {'ESXi', 'CentOS Linux', 'Microsoft Windows', 'Ubuntu Linux'}
    os_version: STRING
    aisle: STRING
    rack: STRING
    position: STRING

  - vm:
    type: {'appliance', 'standalone'}
    role: {'vcenter', 'psc', 'nsx mgr', 'vcd cell'}
    primary_ip_addr: STRING
    primary_mac_addr: STRING
    cpu_core_count: INT
    cpu_socket_count: INT
    memory: INT
    disk_count: INT
    disks:
      disk0: {capacity: FLOAT}
      disk1: {capacity: FLOAT} 
    nic_count: INT
    nics:
      nic0: {ipv4_addr: STRING, ipv4_prefix: INT, ipv4_gateway: STRING, mac_addr: STRING, vlan_id: INT}
      nic1: {ipv6_addr: STRING, ipv6_prefix: INT, ipv6_gateway: STRING, mac_addr: STRING, vlan_id: INT}
    os: {'ESXi', 'CentOS Linux', 'Microsoft Linux', 'Ubuntu Linux'}
    os_version: STRING

- network:
  id: UUID
  type: {'ipv4', 'ipv6'}
  mode: {'routable', 'nonroutable'}
  datacenter: {'wdc', 'sc', 'ams', 'blr'}
  subnet_prefix: INT
  subnet_id: STRING
  broadcast_addr: STRING
  default_gw: STRING
  host_range: {starting_ip: STRING, ending_ip: STRING}
  vlan: INT

- portgroup:
  id: UUID
  name: STRING
  vlan_id: INT
  num_ports: INT
  type: {'ephemeral', 'earlyBinding', 'lateBinding'}
  network_policy:
    - promiscuous: BOOL, default=False
    - mac_changes: BOOL, default=False
    - forged_transmits: BOOL, default=False
  port_policy:
    - traffic_filter_override: BOOL, default=False
    - network_rp_override: BOOL, default=False
    - live_port_move: BOOL, default=False
    - security_override: BOOL, default=False
    - vendor_config_override: BOOL, default=False
    - port_config_reset_disconnect: BOOL, default=True
    - uplink_teaming_override: BOOL, default=True
    - block_override: BOOL, default=True
    - shaping_override: BOOL, default=False
    - vlan_override: BOOL, default=False
    - ipfix_override: BOOL, default=False
  teaming_policy:
    - notify_switches: BOOL, default=True
    - load_balance_policy: {'loadbalance_srcid', 'loadbalance_ip', 'loadbalance_srcmac', 'loadbalance_srcid', 'failover_explicit'}
  vlan_trunk: {'no', 'yes'}, default=No

- vmkernel_port:
  id: UUID
  name: STRING
  portgroup: <link to portgroup CI>
  vlan_id: INT
  vmk_net_type: {'static', 'dhcp'}
  vmk_ip_addr: STRING
  vmk_subnet: STRING
  enabled_ft: BOOL, default=False
  enabled_mgmt: BOOL, default=False
  enabled_vmotion: BOOL, default=False
  enabled_vsan: BOOL, default=False


