---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - sddc_vars.yml

  tasks:
    - name: Create Distributed Virtual Switch
      vmware_dvswitch:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        datacenter_name: '{{ datacenter }}'
        switch_name: '{{ dvs_name }}'
        switch_version: '{{ dvs_version }}'
        mtu: '{{ dvs_mtu }}'
        uplink_quantity: '{{ dvs_uplinks }}'
        discovery_proto: '{{ dvs_discovery_proto }}'
        discovery_operation: '{{ dvs_discovery_op }}'
        state: present

    - name: Add ESXi hosts to DVS
      vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        switch_name: '{{ dvs_name }}'
        esxi_hostname: '{{ item }}'
        vmnics: '{{ vmnics }}'
        state: present
      with_items: '{{ esxi_hostlist }}'

    - name: Create DVS Portgroups
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        portgroup_name: '{{ item.name }}'
        switch_name: '{{ dvs_name }}'
        vlan_id: '{{ item.vlan_id }}'
        num_ports: '{{ item.num_ports }}'
        portgroup_type: '{{ item.portgroup_type }}'
        network_policy:
          promiscuous: yes
          forged_transmits: yes
          mac_changes: yes
        port_policy:
          block_override: yes
          ipfix_override: yes
          live_port_move: yes
          network_rp_override: yes
          port_config_reset_at_disconnect: yes
          security_override: yes
          shaping_override: yes
          traffic_filter_override: yes
          uplink_teaming_override: yes
          vendor_config_override: yes
          vlan_override: yes
        state: present
      with_items: '{{ portgroups }}'

    - name: Migrate vmkernel interfaces to DVS
      vmware_migrate_vmk:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        esxi_hostname: '{{ item }}'
        current_switch_name: '{{ vss_name }}'
        current_portgroup_name: '{{ vss_portgroup }}'
        migrate_switch_name: '{{ dvs_name }}'
        migrate_portgroup_name: '{{ dvs_mgmt_pg }}'
        device: '{{ dvs_mgmt_vmk }}'
      with_items: '{{ esxi_hostlist }}'
