---
- hosts: localhost
  connection: localhost
  gather_facts: False
  vars_files:
    - sddc_vars.yml

  tasks:
    - name: Create vCenter Data Center object
      vmware_datacenter:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        datacenter_name: '{{ datacenter }}'
        state: absent