---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - sddc_vars.yml

  tasks:
    - name: Gather MOID for vSphere Cluster
      vcenter_gather_moids:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter_name: "{{ datacenter }}"
        cluster_name: "{{ cluster }}"
        validate_certs: False
      register: gather_moids_pg
    
    - name: NSX-v cluster preparation
      nsx_cluster_prep:
        nsxmanager_spec: "{{ nsxmanager_spec }}"
        state: absent
        cluster_moid: '{{ gather_moids_pg.object_id }}'
      register: cluster_prep