---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - sddc_vars.yml

  tasks:
    - name: Delete DVS Portgroups
      vmware_dvs_portgroup:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        portgroup_name: '{{ item.name }}'
        switch_name: '{{ dvs_name }}'
        state: absent
      with_items: '{{ portgroups }}'

    - name: Remove ESXi hosts to DVS
      vmware_dvs_host:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        switch_name: '{{ dvs_name }}'
        esxi_hostname: '{{ item }}'
        vmnics: '{{ vmnics }}'
        state: absent
      with_items: '{{ esxi_hostlist }}'

    - name: Delete Distributed Virtual Switch
      vmware_dvswitch:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        datacenter_name: '{{ datacenter }}'
        switch_name: '{{ dvs_name }}'
        state: absent

    

    

    
