---
# Using the ovftool binary, deploys the required appliance(s)
# The failed_when property is used to capture both soft failures ("Monitor failed:") and hard
#  failures (return code > 0)
- include_vars: vault.yml

- name: Deploy the vCenter appliance with embedded PSC
  command: >
    /mnt/vcsa/ovftool/lin64/ovftool
    --acceptAllEulas
    --noSSLVerify
    --X:injectOvfEnv
    --allowExtraConfig
    --X:enableHiddenProperties
    --X:waitForIp
    --X:connectionFileTransferRetryCount=3
    --sourceType=OVA
    --powerOn
    --net:"Network 1"='Management'
    --datastore='local-t410-3TB'
    --diskMode='thin'
    --deploymentOption="medium"
    --prop:guestinfo.cis.appliance.root.shell=/bin/bash
    --prop:guestinfo.cis.deployment.autoconfig=True
    --prop:guestinfo.cis.silentinstall=False
    --prop:guestinfo.cis.vmdir.domain-name="vsphere.local"
    --prop:guestinfo.cis.vmdir.site-name="Default-Site"
    --prop:guestinfo.cis.vmdir.username="administrator@vsphere.local"
    --prop:guestinfo.cis.vmdir.password="82DuQAqu-Rad"
    --prop:guestinfo.cis.appliance.net.addr.family="ipv4"
    --prop:guestinfo.cis.appliance.root.passwd="82DuQAqu-Rad"
    --prop:guestinfo.cis.appliance.ssh.enabled="True"
    --prop:guestinfo.cis.vmdir.first-instance=True
    --prop:guestinfo.cis.ceip_enabled=True
    --prop:guestinfo.cis.appliance.ntp.servers="132.163.96.1,132.163.97.1"
      --name='vcenter'
    --prop:guestinfo.cis.appliance.net.pnid="vcenter.local.domain"
    --prop:guestinfo.cis.appliance.net.mode="static"
    --prop:guestinfo.cis.appliance.net.addr="192.168.0.25"
    --prop:guestinfo.cis.appliance.net.prefix="16"
    --prop:guestinfo.cis.appliance.net.gateway="192.168.0.1"
    --prop:guestinfo.cis.appliance.net.dns.servers="192.168.0.1,192.168.0.2"
      '/mnt/vcsa/VMware-vCenter-Server-Appliance-6.7.0.14000-9451876_OVF10.ova'
    vi://"root":"thAswU53n-CE"@192.168.0.11/
  register: deploy_ovf_cmd_result
  ignore_errors: True
