---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - sddc_vars.yml

  tasks:
    - name: Enable ESXi services
      vmware_host_service_manager:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: False
        cluster_name: '{{ cluster }}'
        service_name: '{{ item }}'
        service_policy: on
        state: present
      with_items: '{{ service_list }}'